---
g_template_config_loop:
  name: Template Config Loop
  zitems:
  - key: config_loop.run.exit_code
    applications:
    - Config Loop
    value_type: int

  - key: config_loop.enabled
    applications:
    - Config Loop
    value_type: int

  ztriggers:
  - name: "config_loop.run.exit_code not zero on {HOST.NAME}"
    expression: "{Template Config Loop:config_loop.run.exit_code.min(#2)}>0"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"
    priority: high

  - name: "No data for config_loop.run.exit_code on {HOST.NAME}"
    expression: "{Template Config Loop:config_loop.run.exit_code.nodata(540m)}=1"
    priority: avg
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"

  - name: "config_loop not enabled {HOST.NAME}"
    expression: "{Template Config Loop:config_loop.enabled.min(#2)}=1"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"
    priority: avg

  - name: "config_loop tag not found on {HOST.NAME}"
    expression: "{Template Config Loop:config_loop.enabled.min(#2)}=2"
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"
    priority: avg

# This might alert if no data is sent. Commenting out for now
#  - name: "No data for config_loop.enabled {HOST.NAME}"
#    expression: "{Template Config Loop:config_loop.enabled.nodata(2880m)}=1"
#    priority: avg
#    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_config_loop.asciidoc"
