---
g_template_psad:
  name: Template PSAD
  zitems:
  - key: psad.found.scanner 
    applications:
    - PSAD
    value_type: int

  ztriggers:
  - name: "PSAD detected port scanning activity"
    expression: "{Template PSAD:psad.found.scanner(#1)}>0"
    url: "https://github.com/openshift/ops-sop/blob/master/v3/alerts/check_psad.asciidoc"
    priority: warning
