---
g_template_heartbeat:
  name: Template Heartbeat
  zitems:
  - name: Heartbeat Ping
    applications:
    - Heartbeat
    key: heartbeat.ping
  ztriggers:
  - name: "Heartbeat.ping has failed (5min) on {HOST.NAME}"
    expression: "{Template Heartbeat:heartbeat.ping.nodata(5m)}=1"
    priority: avg
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_node_heartbeat.asciidoc"

  - name: "Heartbeat.ping has failed (15 min) on {HOST.NAME}"
    expression: "{Template Heartbeat:heartbeat.ping.nodata(15m)}=1"
    priority: high
    url: "https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_node_heartbeat.asciidoc"
